/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardDashBoardLayoutRouteImport } from './routes/dashboard/_dashBoardLayout'
import { Route as AuthAuthLayoutRouteImport } from './routes/auth/_authLayout'
import { Route as visiteurGuestLayoutRouteImport } from './routes/(visiteur)/_guestLayout'
import { Route as DashboardDashBoardLayoutIndexRouteImport } from './routes/dashboard/_dashBoardLayout/index'
import { Route as visiteurGuestLayoutIndexRouteImport } from './routes/(visiteur)/_guestLayout/index'
import { Route as AuthAuthLayoutRegisterRouteImport } from './routes/auth/_authLayout/register'
import { Route as AuthAuthLayoutLoginRouteImport } from './routes/auth/_authLayout/login'

const DashboardRouteImport = createFileRoute('/dashboard')()
const AuthRouteImport = createFileRoute('/auth')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashBoardLayoutRoute =
  DashboardDashBoardLayoutRouteImport.update({
    id: '/_dashBoardLayout',
    getParentRoute: () => DashboardRoute,
  } as any)
const AuthAuthLayoutRoute = AuthAuthLayoutRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => AuthRoute,
} as any)
const visiteurGuestLayoutRoute = visiteurGuestLayoutRouteImport.update({
  id: '/(visiteur)/_guestLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashBoardLayoutIndexRoute =
  DashboardDashBoardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashBoardLayoutRoute,
  } as any)
const visiteurGuestLayoutIndexRoute =
  visiteurGuestLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => visiteurGuestLayoutRoute,
  } as any)
const AuthAuthLayoutRegisterRoute = AuthAuthLayoutRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)
const AuthAuthLayoutLoginRoute = AuthAuthLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardDashBoardLayoutRouteWithChildren
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/': typeof visiteurGuestLayoutIndexRoute
  '/dashboard/': typeof DashboardDashBoardLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthAuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardDashBoardLayoutIndexRoute
  '/auth/login': typeof AuthAuthLayoutLoginRoute
  '/auth/register': typeof AuthAuthLayoutRegisterRoute
  '/': typeof visiteurGuestLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(visiteur)/_guestLayout': typeof visiteurGuestLayoutRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/auth/_authLayout': typeof AuthAuthLayoutRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_dashBoardLayout': typeof DashboardDashBoardLayoutRouteWithChildren
  '/auth/_authLayout/login': typeof AuthAuthLayoutLoginRoute
  '/auth/_authLayout/register': typeof AuthAuthLayoutRegisterRoute
  '/(visiteur)/_guestLayout/': typeof visiteurGuestLayoutIndexRoute
  '/dashboard/_dashBoardLayout/': typeof DashboardDashBoardLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/dashboard' | '/auth/login' | '/auth/register' | '/'
  id:
    | '__root__'
    | '/(visiteur)/_guestLayout'
    | '/auth'
    | '/auth/_authLayout'
    | '/dashboard'
    | '/dashboard/_dashBoardLayout'
    | '/auth/_authLayout/login'
    | '/auth/_authLayout/register'
    | '/(visiteur)/_guestLayout/'
    | '/dashboard/_dashBoardLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  visiteurGuestLayoutRoute: typeof visiteurGuestLayoutRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_dashBoardLayout': {
      id: '/dashboard/_dashBoardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashBoardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/_authLayout': {
      id: '/auth/_authLayout'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/(visiteur)/_guestLayout': {
      id: '/(visiteur)/_guestLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof visiteurGuestLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_dashBoardLayout/': {
      id: '/dashboard/_dashBoardLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashBoardLayoutIndexRouteImport
      parentRoute: typeof DashboardDashBoardLayoutRoute
    }
    '/(visiteur)/_guestLayout/': {
      id: '/(visiteur)/_guestLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof visiteurGuestLayoutIndexRouteImport
      parentRoute: typeof visiteurGuestLayoutRoute
    }
    '/auth/_authLayout/register': {
      id: '/auth/_authLayout/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthLayoutRegisterRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
    '/auth/_authLayout/login': {
      id: '/auth/_authLayout/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLayoutLoginRouteImport
      parentRoute: typeof AuthAuthLayoutRoute
    }
  }
}

interface visiteurGuestLayoutRouteChildren {
  visiteurGuestLayoutIndexRoute: typeof visiteurGuestLayoutIndexRoute
}

const visiteurGuestLayoutRouteChildren: visiteurGuestLayoutRouteChildren = {
  visiteurGuestLayoutIndexRoute: visiteurGuestLayoutIndexRoute,
}

const visiteurGuestLayoutRouteWithChildren =
  visiteurGuestLayoutRoute._addFileChildren(visiteurGuestLayoutRouteChildren)

interface AuthAuthLayoutRouteChildren {
  AuthAuthLayoutLoginRoute: typeof AuthAuthLayoutLoginRoute
  AuthAuthLayoutRegisterRoute: typeof AuthAuthLayoutRegisterRoute
}

const AuthAuthLayoutRouteChildren: AuthAuthLayoutRouteChildren = {
  AuthAuthLayoutLoginRoute: AuthAuthLayoutLoginRoute,
  AuthAuthLayoutRegisterRoute: AuthAuthLayoutRegisterRoute,
}

const AuthAuthLayoutRouteWithChildren = AuthAuthLayoutRoute._addFileChildren(
  AuthAuthLayoutRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthLayoutRoute: typeof AuthAuthLayoutRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthLayoutRoute: AuthAuthLayoutRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardDashBoardLayoutRouteChildren {
  DashboardDashBoardLayoutIndexRoute: typeof DashboardDashBoardLayoutIndexRoute
}

const DashboardDashBoardLayoutRouteChildren: DashboardDashBoardLayoutRouteChildren =
  {
    DashboardDashBoardLayoutIndexRoute: DashboardDashBoardLayoutIndexRoute,
  }

const DashboardDashBoardLayoutRouteWithChildren =
  DashboardDashBoardLayoutRoute._addFileChildren(
    DashboardDashBoardLayoutRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashBoardLayoutRoute: typeof DashboardDashBoardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashBoardLayoutRoute: DashboardDashBoardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  visiteurGuestLayoutRoute: visiteurGuestLayoutRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
